version: '3'
services:
    jenkins:
        container_name: jenkins
        image: jenkins-docker:latest
        ports:
            - "8080:8080"
            - "50000:50000"
        volumes:
            - ./docker/jenkins/:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/bin/docker:/usr/bin/docker